#ifndef ENUMS_H
#define ENUMS_H

enum Tasks {
    TASK_UPDATE_CURRENCIES_BASE = 0,
    TASK_UPDATE_CURRENCIES_INFO,
    TASK_UPDATE_CURRENCIES_DEV,
};

enum TaskErr {
    ERR_TASK_OK = 0,
    ERR_TASK_DOWNLOAD_PAGE_FOR_PARSE_FAIL,
    ERR_TASK_PARSE_PAGE_FAIL,
};

#endif // ENUMS_H
